package com.platformcommons.platform.service.iam.application.constant;

public final class TenantConfigConstant {

    public static final String CONFIG_KEY_USER_VERIFICATION_REQUIRED = "CONFIG_KEY.USER_VERIFICATION_REQUIRED";

    public static final String CONFIG_KEY_TENANT_MAILS_FOR_NOTIFICATION = "CONFIG_KEY.TENANT_MAILS_FOR_NOTIFICATION";

    public static final String  CONFIG_KEY_WORKFORCE_LINKED_APPLICANTS_FILTER = "CONFIG_KEY.WORKFORCE_LINKED_APPLICANTS_FILTER";

    public static final String  CONFIG_KEY_COMMUNITY_LINKED_APPLICANT_FILTER = "CONFIG_KEY.COMMUNITY_LINKED_APPLICANT_FILTER";

    public static final String  CONFIG_KEY_SUPERVISOR_LINKED_APPLICANT_FILTER = "CONFIG_KEY.SUPERVISOR_LINKED_APPLICANT_FILTER";

    public static final String CONFIG_KEY_TENANT_SUPPORT_EMAILS = "CONFIG_KEY.TENANT_SUPPORT_EMAILS";

    public static final String CONFIG_KEY_TENANT_SUPPORT_CONTACT_NUMBERS = "CONFIG_KEY.TENANT_SUPPORT_CONTACT_NUMBERS";

}
