package com.platformcommons.platform.service.iam.application.constant;

public final class TenantMetaConstant {

    public static final String META_MASTER_ROLE_CODES = "META_MASTER.TENANT_ROLES";
    public static final String META_MASTER_DATA_SET_GROUPS = "META_MASTER.DATA_SET_GROUPS";
    public static final String META_MASTER_DATA_DEFAULT_DOMAIN= "META_MASTER.DEFAULT_DOMAIN";
    public static final String META_MASTER_DATA_SEND_WELCOME_MAIL_ON_SIGNUP= "META_MASTER.SEND_WELCOME_MAIL_ON_SIGNUP";
    public static final String META_MASTER_ALLOWED_SELF_REGISTER = "META_MASTER.ALLOW_SELF_REGISTER";
    public static final String META_MASTER_ALLOWED_JOIN_USER = "META_MASTER.ALLOW_JOIN_USER";
    public static final String META_MASTER_DEFAULT_USER_STATUS = "META_MASTER.SELF_REGISTER_STATUS";
    public static final String META_MASTER_DEFAULT_JOIN_USER_STATUS = "META_MASTER.JOIN_USER_STATUS";
    public static final String META_MASTER_ALLOWED_PARTNER_SIGNUP = "META_MASTER.ALLOW_PARTNER_SIGNUP";
    public static final String META_MASTER_PARTNER_SIGNUP_DEFAULT_STATUS = "APPROVED";


    public static final String TENANT_METADATA_CODE_RESET_PASSWORD_MAIL_SUBJECT = "MD.TENANT_METADATA_CODE_RESET_PASSWORD_MAIL_SUBJECT";
    public static final String TENANT_METADATA_CODE_RESET_PASSWORD_MAIL_CODE = "MD.TENANT_METADATA_CODE_RESET_PASSWORD_MAIL_CODE";
    public static final String TENANT_METADATA_CODE_RESET_PASSWORD_SMS_CODE = "MD.TENANT_METADATA_CODE_RESET_PASSWORD_SMS_CODE";

    public static final String TENANT_METADATA_DEFAULT_COUNTRY_DIAL_CODE = "MD.TENANT_METADATA_DEFAULT_COUNTRY_DIAL_CODE";

    public static final String TENANT_METADATA_CODE_LOGIN_ATTEMPTS = "MD.USER_NUM_FAILED_LOGIN_ATTEMPTS";
    public static final String TENANT_METADATA_CODE_OPT_VERIFICATION_TIMEOUT = "MD.USER_NUM_FAILED_OTP_VERIFICATION_TIMEOUT";

    public static final String TENANT_METADATA_FORGET_PASS_OTP_EXPIRY = "MD.FORGET_PASS_OTP_EXPIRY";
    public static final String TENANT_METADATA_FORGET_PASS_TIMOUT = "MD.FORGET_PASS_TIMOUT";
    public static final String TENANT_METADATA_SELF_REGISTRATION_OTP_EXPIRY = "MD.SELF_REGISTRATION_OTP_EXPIRY";
    public static final String TENANT_METADATA_LOGIN_REQUEST_OTP_EXPIRY = "MD.LOGIN_REQUEST_OTP_EXPIRY";
    public static final String TENANT_METADATA_USER_SELF_REGISTRATION = "MD.USER_SELF_REGISTRATION";
    public static final String META_MASTER_USER_MOBILE_AS_LOGIN = "META_MASTER.USER_MOBILE_AS_LOGIN";


}
