package com.platformcommons.platform.service.search.application.constant;

public class MessagingConstant {
    public static final String BRBASE_USER_UPDATED="BRBASE_USER_UPDATED";

    public static final String BRBASE_USER_CREATED="BRBASE_USER_CREATED";

    public static final String BRBASE_USER_DELETED="BRBASE_USER_DELETED";

    public static final String GROUP_ID="COMMONS-SEARCH-SERVICE";

    public static  final String APP_CREATED="COMMONS_DOMAIN_SERVICE.APP_CREATED";  // EventDTO<AppEventDTO>

    public static  final String APP_UPDATED="COMMONS_DOMAIN_SERVICE.APP_UPDATED";

    public static  final String DOMAIN_CREATED="COMMONS_DOMAIN_SERVICE.DOMAIN_CREATED"; // EventDTO<DomainEventDTO>

    public static  final String DOMAIN_UPDATED="COMMONS_DOMAIN_SERVICE.DOMAIN_UPDATED";

    public static  final String DOMAIN_HIERARCHY_CREATED="COMMONS_DOMAIN_SERVICE.DOMAIN_HIERARCHY_CREATED"; // EventDTO<DomainHIERARCHYEventDTO>

    public static  final String DOMAIN_HIERARCHY_UPDATED="COMMONS_DOMAIN_SERVICE.DOMAIN_HIERARCHY_UPDATED";

    public static  final String USE_CASE_CREATED="COMMONS_DOMAIN_SERVICE.USE_CASE_CREATED"; // EventDTO<UseCaseEventDTO>

    public static  final String USE_CASE_UPDATED="COMMONS_DOMAIN_SERVICE.USE_CASE_UPDATED";

    public  static  final String TMA_CHANNEL_PRODUCT_CREATED = "COMMONS_MARKET_SERVICE.TMA_CHANNEL_PRODUCT_CREATED";

    public  static  final String TMA_CHANNEL_PRODUCT_UPDATED = "COMMONS_MARKET_SERVICE.TMA_CHANNEL_PRODUCT_UPDATED";

    public  static  final String TMA_CHANNEL_PRODUCT_DELETED_FOR_SEARCH_SERVICE = "COMMONS_MARKET_SERVICE.TMA_CHANNEL_PRODUCT_DELETED_FOR_SEARCH_SERVICE";

    public  static  final String TMA_CHANNEL_SOLUTION_CREATED = "COMMONS_MARKET_SERVICE.TMA_CHANNEL_SOLUTION_CREATED";

    public  static  final String TMA_CHANNEL_SOLUTION_DELETED_FOR_SEARCH_SERVICE = "COMMONS_MARKET_SERVICE.TMA_CHANNEL_SOLUTION_DELETED_FOR_SEARCH_SERVICE";

    public  static  final String PRODUCT_GP_GPV_UPDATED_FOR_SEARCH_SERVICE = "COMMONS_MARKET_SERVICE.PRODUCT_GP_GPV_UPDATED_FOR_SEARCH_SERVICE";

    public static final String GENERIC_PRODUCT_VARIETY_CREATED_OR_UPDATED = "COMMONS_PRODUCT_SERVICE.GENERIC_PRODUCT_VARIETY_CREATED_OR_UPDATED";

    public static final String GENERIC_PRODUCT_CREATED_OR_UPDATED = "COMMONS_PRODUCT_SERVICE.GENERIC_PRODUCT_CREATED_OR_UPDATED";

    public  static  final String TRADER_CREATED = "COMMONS_MARKET_SERVICE.TRADER_CREATED";

    public  static  final String TRADER_UPDATED= "COMMONS_MARKET_SERVICE.TRADER_UPDATED";

    public static final String CREATE_PRODUCT_DTO = "COMMONS_PRODUCT_SERVICE.PRODUCT_DELETED_V1";

    public static  final String OPPORTUNITY_CREATED = "OPPORTUNITY_CREATED";

    public static  final String OPPORTUNITY_UPDATED = "OPPORTUNITY_UPDATED";

    public static  final String OPPORTUNITY_DELETED = "OPPORTUNITY_DELETED";

    public static  final String OPPORTUNITY_SYNC = "OPPORTUNITY_SYNC";

    public static  final String TAG_CREATED="COMMONS_DOMAIN_SERVICE.TAG_CREATED";  // EventDTO<TagDTO>

    public static  final String TAG_UPDATED="COMMONS_DOMAIN_SERVICE.TAG_UPDATED";

    public static final String CREATE_GENERIC_SOLUTION_DTO = "COMMONS_PRODUCT_SERVICE.GENERIC_SOLUTION_CREATED";

    public static final String CREATE_SOLUTION_RESOURCE_MAP_DTO = "COMMONS_PRODUCT_SERVICE.SOLUTION_RESOURCE_MAP_CREATED";

    public static final String DELETE_SOLUTION_RESOURCE_MAP_DTO = "COMMONS_PRODUCT_SERVICE.SOLUTION_RESOURCE_MAP_DELETED";

    public static  final String OPPORTUNITY_STAKE_HOLDER_ADDED = "OPPORTUNITY_STAKE_HOLDER_ADDED";

    public static  final String OPPORTUNITY_STAKE_HOLDER_DELETED = "OPPORTUNITY_STAKE_HOLDER_DELETED";

    public static final String USER_FACT_SYNC = "USER_FACT_SYNC";

    public static final String USER_FACT_CREATED_OR_UPDATED = "USER_FACT_CREATED_OR_UPDATED";

    public static final String USER_FACT_DELETED = "USER_FACT_DELETED";

    public static final String BRBASE_USER_NEW_ROLE_ASSIGNED = "BRBASE_USER_NEW_ROLE_ASSIGNED";

    public static final String BRBASE_USER_ROLE_UPDATED = "BRBASE_USER_ROLE_UPDATED";

    public static final String BRBASE_USER_ROLE_DELETED = "BRBASE_USER_ROLE_DELETED";

    public static  final String COMMONS_WORKFORCE_CREATED = "COMMONS_WORKFORCE_CREATED";

    public static  final String COMMONS_WORKFORCE_UPDATED = "COMMONS_WORKFORCE_UPDATED";

    public static final String POST_CREATED = "POST_CREATED";

    public static final String POST_UPDATED = "POST_UPDATED";

    public static final String POST_UPDATED_BULK = "POST_UPDATED_BULK";

    public static final String POST_DELETED = "POST_DELETED";

    public static final String POST_SYNC = "POST_SYNC";

    public static  final String OPPORTUNITY_APPLICANT_CREATE = "OPPORTUNITY_APPLICANT_CREATE";

    public static  final String OPPORTUNITY_APPLICANT_UPDATE = "OPPORTUNITY_APPLICANT_UPDATE";

    public static  final String OPPORTUNITY_APPLICANT_UPDATE_BULK = "OPPORTUNITY_APPLICANT_UPDATE_BULK";

    public static  final String OPPORTUNITY_APPLICANT_DELETE = "OPPORTUNITY_APPLICANT_DELETE";

    public static  final String OPPORTUNITY_APPLICANT_SYNC = "OPPORTUNITY_APPLICANT_SYNC";

    public static final String OPPORTUNITY_APPLICANT_ATTENDANCE_UPDATED = "OPPORTUNITY_APPLICANT_ATTENDANCE_UPDATED";

    public static final String OPPORTUNITY_APPLICANT_ATTENDANCE_UPDATED_BULK = "OPPORTUNITY_APPLICANT_ATTENDANCE_UPDATED_BULK";

    public static final String OPPORTUNITY_APPLICANT_RULE_RESULT_CREATED = "OPPORTUNITY_APPLICANT_RULE_RESULT_CREATED";

    public static  final String OPPORTUNITY_APPLICANT_META_CREATE = "OPPORTUNITY_APPLICANT_META_CREATE";

    public static  final String OPPORTUNITY_APPLICANT_META_UPDATE = "OPPORTUNITY_APPLICANT_META_UPDATE";

    public static final String OPPORTUNITY_APPLICANT_OWNER_RESULT_CREATED = "OPPORTUNITY_APPLICANT_OWNER_RESULT_CREATED";

    public static final String OPPORTUNITY_APPLICANT_OWNER_RESULT_UPDATED = "OPPORTUNITY_APPLICANT_OWNER_RESULT_UPDATED";

    public static final String OPPORTUNITY_TENANT_DETAILS_UPDATED = "OPPORTUNITY_TENANT_DETAILS_UPDATED";

    public static final String OPPORTUNITY_APPLICANT_ONBOARDING_CREATED = "OPPORTUNITY_APPLICANT_ONBOARDING_CREATED";

    public static final String OPPORTUNITY_APPLICANT_ONBOARDING_UPDATED = "OPPORTUNITY_APPLICANT_ONBOARDING_UPDATED";

    public static final String OPPORTUNITY_APPLICANT_UPDATE_ON_RECRUITER_OR_COMMITTEE_ASSIGNED_BULK = "OPPORTUNITY_APPLICANT_UPDATE_ON_RECRUITER_OR_COMMITTEE_ASSIGNED_BULK";

    public static final String GENERIC_PRODUCT_DELETED_V2 = "COMMONS_PRODUCT_SERVICE.GENERIC_PRODUCT_DELETED_V2";

    public static final String GENERIC_PRODUCT_VARIETY_DELETED = "COMMONS_PRODUCT_SERVICE.GENERIC_PRODUCT_VARIETY_DELETED";

    public static final String GENERIC_PRODUCT_VARIETY_RETAGGED_FOR_SEARCH_SERVICE = "COMMONS_PRODUCT_SERVICE.GENERIC_PRODUCT_VARIETY_RETAGGED_FOR_SEARCH_SERVICE";

    public static final String GENERIC_PRODUCT_VARIETY_RETAGGED_FOR_SEARCH_SERVICE_SUCCESS = "COMMONS_PRODUCT_SERVICE.GENERIC_PRODUCT_VARIETY_RETAGGED_FOR_SEARCH_SERVICE_SUCCESS";

    public static final String GENERIC_PRODUCT_VARIETY_RETAGGED_FOR_SEARCH_SERVICE_FAILURE = "COMMONS_PRODUCT_SERVICE.GENERIC_PRODUCT_VARIETY_RETAGGED_FOR_SEARCH_SERVICE_FAILURE";

    public static final String OPPORTUNITY_APPLICANT_TASK_CREATED = "OPPORTUNITY_APPLICANT_TASK_CREATED";

    public static final String OPPORTUNITY_APPLICANT_TASK_UPDATED = "OPPORTUNITY_APPLICANT_TASK_UPDATED";

    public static final String OPPORTUNITY_APPLICANT_TASK_CREATED_BULK = "OPPORTUNITY_APPLICANT_TASK_CREATED_BULK";

    public static final String OPPORTUNITY_APPLICANT_TASK_DELETED = "OPPORTUNITY_APPLICANT_TASK_DELETED";

    public static final String OPPORTUNITY_APPLICANT_ASSESSMENT_DATA_POST = "OPPORTUNITY_APPLICANT_ASSESSMENT_DATA_POST";

    public MessagingConstant() {
    }
}
