package com.platformcommons.platform.service.search.application.constant;

import java.util.*;

public final class TenantConfigConstant {

    public static final String DEFAULT_APP_CONTEXT = "PLATFORM";

    public static final String  CONFIG_KEY_WORKFORCE_LINKED_APPLICANTS_FILTER = "CONFIG_KEY.WORKFORCE_LINKED_APPLICANTS_FILTER";

    public static final String  CONFIG_KEY_COMMUNITY_LINKED_APPLICANT_FILTER = "CONFIG_KEY.COMMUNITY_LINKED_APPLICANT_FILTER";

    public static final String  CONFIG_KEY_SUPERVISOR_LINKED_APPLICANT_FILTER = "CONFIG_KEY.SUPERVISOR_LINKED_APPLICANT_FILTER";

    public static final String CONFIG_KEY_VISIBLE_TO_ROLE_FILTER_FOR_OPPORTUNITY_FETCH = "CONFIG_KEY.VISIBLE_TO_ROLE_FILTER_FOR_OPPORTUNITY_FETCH";

    public static final String CONFIG_KEY_SHOW_ALL_OPPORTUNITIES_TO_USERS_FOR_VISIBLE_TO_ROLE_IS_NULL = "CONFIG_KEY.SHOW_ALL_OPPORTUNITIES_TO_USERS_FOR_VISIBLE_TO_ROLE_IS_NULL";

    public static final String CONFIG_KEY_FETCH_COHORT_AND_PLACEMENT_CITY = "CONFIG_KEY.FETCH_COHORT_AND_PLACEMENT_CITY";

    public static final String CONFIG_KEY_ROLE_CODES_TO_VIEW_OPEN_TO_WORK_USERS_ONLY = "CONFIG_KEY.ROLE_CODES_TO_VIEW_OPEN_TO_WORK_USERS_ONLY";

    public static final String CONFIG_KEY_ORGANISATION_REPRESENTATIVE_ROLE_CODE_SUFFIX = "CONFIG_KEY.ORGANISATION_REPRESENTATIVE_ROLE_CODE_SUFFIX";

    public static final String CONFIG_KEY_EMPLOYER_ROLE_CODES = "CONFIG_KEY.EMPLOYER_ROLE_CODES";


    public static final Map<String, String> DEFAULT_SINGLE_VALUE_CONFIG_MAP = new HashMap<>();

    public static final Map<String, Set<String>> DEFAULT_MULTI_VALUE_CONFIG_MAP = new HashMap<>();

    static {
        DEFAULT_SINGLE_VALUE_CONFIG_MAP.put(CONFIG_KEY_WORKFORCE_LINKED_APPLICANTS_FILTER, "1");
        DEFAULT_SINGLE_VALUE_CONFIG_MAP.put(CONFIG_KEY_COMMUNITY_LINKED_APPLICANT_FILTER, "1");
        DEFAULT_SINGLE_VALUE_CONFIG_MAP.put(CONFIG_KEY_SUPERVISOR_LINKED_APPLICANT_FILTER, "1");
        DEFAULT_SINGLE_VALUE_CONFIG_MAP.put(CONFIG_KEY_VISIBLE_TO_ROLE_FILTER_FOR_OPPORTUNITY_FETCH, "0");
        DEFAULT_SINGLE_VALUE_CONFIG_MAP.put(CONFIG_KEY_SHOW_ALL_OPPORTUNITIES_TO_USERS_FOR_VISIBLE_TO_ROLE_IS_NULL, "0");
        DEFAULT_SINGLE_VALUE_CONFIG_MAP.put(CONFIG_KEY_FETCH_COHORT_AND_PLACEMENT_CITY, "0");
        DEFAULT_SINGLE_VALUE_CONFIG_MAP.put(CONFIG_KEY_ORGANISATION_REPRESENTATIVE_ROLE_CODE_SUFFIX, null);

        DEFAULT_MULTI_VALUE_CONFIG_MAP.put(CONFIG_KEY_ROLE_CODES_TO_VIEW_OPEN_TO_WORK_USERS_ONLY, null);
        DEFAULT_MULTI_VALUE_CONFIG_MAP.put(CONFIG_KEY_EMPLOYER_ROLE_CODES, null);
    }

}
