openapi: 3.0.0
info:
  title: test
  version: '1.0'
tags:
 - name: AppMenu
 - name: AppOperation
 - name: AppRbac

paths:
  /api/v1/app-menu/page:
    get:
      summary: Get By Page
      tags:
        - AppMenu
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AppMenu'
      operationId: get-app-menu-page
      parameters:
        - schema:
            type: integer
            format: int32
          in: query
          name: page
          required: true
        - schema:
            type: integer
            format: int32
          in: query
          name: size
          required: true
  /api/v1/app-menu:
    get:
      summary: Get By Id
      tags:
        - AppMenu
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppMenu'
      operationId: get-app-menu
      parameters:
        - schema:
            type: integer
            format: int64
          in: query
          name: id
          required: true
    post:
      summary: ''
      operationId: post-app-menu
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: integer
                format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppMenu'
      tags:
        - AppMenu
    put:
      summary: ''
      operationId: put-app-menu
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppMenu'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppMenu'
      tags:
        - AppMenu
      description: ''
    delete:
      summary: ''
      operationId: delete-app-menu
      responses:
        '204':
          description: No Content
      parameters:
        - schema:
            type: integer
            format: int64
          in: query
          name: id
          required: true
        - schema:
            type: string
          in: query
          name: reason
          required: true
      tags:
        - AppMenu
  /api/v1/app-operation/page:
    get:
      summary: Get By Page
      tags:
        - AppOperation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AppOperation'
      operationId: get-app-operation-page
      parameters:
        - schema:
            type: integer
            format: int32
          in: query
          name: page
          required: true
        - schema:
            type: integer
            format: int32
          in: query
          name: size
          required: true
  /api/v1/app-operation:
    get:
      summary: Get By Id
      tags:
        - AppOperation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppOperation'
      operationId: get-app-operation
      parameters:
        - schema:
            type: integer
            format: int64
          in: query
          name: id
          required: true
    post:
      summary: ''
      operationId: post-app-operation
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: integer
                format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppOperation'
      tags:
        - AppOperation
    put:
      summary: ''
      operationId: put-app-operation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppOperation'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppOperation'
      tags:
        - AppOperation
      description: ''
    delete:
      summary: ''
      operationId: delete-app-operation
      responses:
        '204':
          description: No Content
      parameters:
        - schema:
            type: integer
            format: int64
          in: query
          name: id
          required: true
        - schema:
            type: string
          in: query
          name: reason
          required: true
      tags:
        - AppOperation
  /api/v1/app-rbac/page:
    get:
      summary: Get By Page
      tags:
        - AppRbac
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AppRbac'
      operationId: get-app-rbac-page
      parameters:
        - schema:
            type: integer
            format: int32
          in: query
          name: page
          required: true
        - schema:
            type: integer
            format: int32
          in: query
          name: size
          required: true
  /api/v1/app-rbac:
    get:
      summary: Get By Id
      tags:
        - AppRbac
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppRbac'
      operationId: get-app-rbac
      parameters:
        - schema:
            type: integer
            format: int64
          in: query
          name: id
          required: true
    post:
      summary: ''
      operationId: post-app-rbac
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: integer
                format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppRbac'
      tags:
        - AppRbac
    put:
      summary: ''
      operationId: put-app-rbac
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppRbac'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppRbac'
      tags:
        - AppRbac
      description: ''
    delete:
      summary: ''
      operationId: delete-app-rbac
      responses:
        '204':
          description: No Content
      parameters:
        - schema:
            type: integer
            format: int64
          in: query
          name: id
          required: true
        - schema:
            type: string
          in: query
          name: reason
          required: true
      tags:
        - AppRbac

components:
  schemas:
    AppMenu:
      title: AppMenu
      type: object
      properties:
        id:
          type: integer
          format: int64
        parentMenu:
          type: integer
          format: int64
        appRbac:
          type: integer
          format: int64
        menuCode:
          type: string
        sequence:
          type: integer
          format: int64
        isRoot:
          type: boolean
        isEnabled:
          type: boolean
        appMenuList:
          type: array
          items:
            $ref: '#/components/schemas/AppMenu'
    AppOperation:
      title: AppOperation
      type: object
      properties:
        id:
          type: integer
          format: int64
        appRbac:
          type: integer
          format: int64
        entity:
          type: string
        create:
          type: boolean
        update:
          type: boolean
        read:
          type: boolean
        delete:
          type: boolean
        isDirect:
          type: boolean
        linkedMenuCode:
          type: string
        group:
          type: string
    AppRbac:
      title: AppRbac
      type: object
      properties:
        id:
          type: integer
          format: int64
        appCode:
          type: string
        isDefault:
          type: boolean
        appRole:
          type: string
        appMenuList:
          type: array
          items:
            $ref: '#/components/schemas/AppMenu'
        appOperationList:
          type: array
          items:
            $ref: '#/components/schemas/AppOperation'
