openapi: 3.0.0
info:
  title: App-Service
  version: '1.0'
tags:
  - name: App
  - name: AppConfig
  - name: AppVersion
  - name: AppConfigScopeMaster
paths:
  /api/v1/apps/page:
    get:
      summary: Get by Page
      tags:
        - App
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/App'
      operationId: get-apps-page
      parameters:
        - schema:
            type: integer
            format: int32
          in: query
          name: page
          required: true
        - schema:
            type: integer
            format: int32
          in: query
          name: size
          required: true
  /api/v1/apps:
    get:
      summary: Get By Id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/App'
      operationId: get-apps
      parameters:
        - schema:
            type: integer
            format: int64
          in: query
          name: id
          required: true
      tags:
        - App
    post:
      summary: saveApp
      operationId: post-apps
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: integer
                format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/App'
      tags:
        - App
    put:
      summary: ''
      operationId: put-apps
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/App'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/App'
      tags:
        - App
    delete:
      summary: ''
      operationId: delete-apps
      responses:
        '204':
          description: No Content
      parameters:
        - schema:
            type: integer
            format: int64
          in: query
          name: id
          required: true
        - schema:
            type: string
          in: query
          name: reason
          required: true
      tags:
        - App
  /api/v1/app-config/page:
    get:
      summary: Get By Page
      tags:
        - AppConfig
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AppConfig'
      operationId: get-app-configs-page
      parameters:
        - schema:
            type: integer
            format: int32
          in: query
          name: page
          required: true
        - schema:
            type: integer
            format: int32
          in: query
          name: size
          required: true
  /api/v1/app-config:
    get:
      summary: Get By Id
      tags:
        - AppConfig
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppConfig'
      operationId: get-app-configs
      parameters:
        - schema:
            type: integer
            format: int64
          in: query
          name: id
          required: true
    post:
      summary: saveApp
      operationId: post-app-config
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: integer
                format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppConfig'
      tags:
        - AppConfig
    put:
      summary: ''
      operationId: put-app-config
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppConfig'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppConfig'
      tags:
        - AppConfig
    delete:
      summary: ''
      operationId: delete-app-config
      responses:
        '204':
          description: No Content
      parameters:
        - schema:
            type: integer
            format: int64
          in: query
          name: id
          required: true
        - schema:
            type: string
          in: query
          name: reason
          required: true
      tags:
        - AppConfig
  '/api/v1/app-version/{appVersionId}/app-config':
    post:
      summary: Add AppConfig to AppVersion
      operationId: post-api-v1-app-config-add
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/AppConfig'
      responses:
        '204':
          description: No Content
      tags:
        - AppConfig
      parameters:
        - schema:
            type: integer
            format: int64
          in: path
          name: appVersionId
          required: true
  /api/v1/app-config-scope-master/page:
    get:
      summary: Get By Page
      tags:
        - AppConfigScopeMaster
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AppConfigScopeMaster'
      operationId: get-app-config-scope-master-page
      parameters:
        - schema:
            type: integer
            format: int32
          in: query
          name: page
          required: true
        - schema:
            type: integer
            format: int32
          in: query
          name: size
          required: true
  /api/v1/app-config-scope-master:
    get:
      summary: Get By Id
      tags:
        - AppConfigScopeMaster
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppConfigScopeMaster'
      operationId: get-app-config-scope-master
      parameters:
        - schema:
            type: integer
            format: int64
          in: query
          name: id
          required: true
    post:
      summary: saveApp
      operationId: post-app-config-scope-master
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: integer
                format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppConfigScopeMaster'
      tags:
        - AppConfigScopeMaster
    put:
      summary: ''
      operationId: put-app-config-scope-master
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppConfigScopeMaster'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppConfigScopeMaster'
      tags:
        - AppConfigScopeMaster
      description: ''
    delete:
      summary: ''
      operationId: delete-app-config-scope-master
      responses:
        '204':
          description: No Content
      parameters:
        - schema:
            type: integer
            format: int64
          in: query
          name: id
          required: true
        - schema:
            type: string
          in: query
          name: reason
          required: true
      tags:
        - AppConfigScopeMaster
  /api/v1/app-version/page:
    get:
      summary: Get By Page
      tags:
        - AppVersion
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AppVersion'
      operationId: get-app-version-page
      parameters:
        - schema:
            type: integer
            format: int32
          in: query
          name: page
          required: true
        - schema:
            type: integer
            format: int32
          in: query
          name: size
          required: true
  /api/v1/app-version:
    get:
      summary: Get By Id
      tags:
        - AppVersion
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppVersion'
      operationId: get-app-version
      parameters:
        - schema:
            type: integer
            format: int64
          in: query
          name: id
          required: true
    post:
      summary: saveApp
      operationId: post-app-version
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: integer
                format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppVersion'
      tags:
        - AppVersion
      description: ''
    put:
      summary: ''
      operationId: put-app-version
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppVersion'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppVersion'
      tags:
        - AppVersion
    delete:
      summary: ''
      operationId: delete-app-version
      responses:
        '204':
          description: No Content
      parameters:
        - schema:
            type: integer
            format: int64
          in: query
          name: id
          required: true
        - schema:
            type: string
          in: query
          name: reason
          required: true
      tags:
        - AppVersion
      description: ''
  '/api/v1/apps/{appId}/app-version':
    post:
      summary: Add AppVersion to App
      operationId: post-api-v1-app-version-add
      responses:
        '204':
          description: No Content
      parameters:
        - schema:
            type: integer
            format: int64
          in: path
          name: appId
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/AppVersion'
      tags:
        - AppVersion
components:
  schemas:
    App:
      title: App
      type: object
      properties:
        id:
          type: integer
          format: int64
        apiKey:
          type: string
        code:
          type: string
        name:
          type: string
        appVersionList:
          type: array
          items:
            $ref: '#/components/schemas/AppVersion'
    AppConfig:
      title: AppConfig
      type: object
      properties:
        id:
          type: integer
          format: int64
        scopeCode:
          type: string
        scopeValue:
          type: string
        configKey:
          type: string
        configValue:
          type: string
        configType:
          type: string
        configValueML:
          type: array
          items:
            $ref: '#/components/schemas/MLText'
        notes:
          type: string
    AppConfigScopeMaster:
      title: AppConfigScopeMaster
      type: object
      properties:
        id:
          type: integer
          format: int64
        code:
          type: string
        priority:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        dataType:
          type: string
    AppVersion:
      title: AppVersion
      type: object
      properties:
        id:
          type: integer
          format: int64
        version:
          type: string
        versionSequence:
          type: string
        isDeprecated:
          type: integer
          format: int32
        appConfigList:
          type: array
          items:
            $ref: '#/components/schemas/AppConfig'
    Config:
      title: Config
      type: object
      properties:
        id:
          type: integer
          format: int64
        configKey:
          type: string
        configType:
          type: string
        configValue:
          type: string
        configValueML:
          type: array
          items:
            $ref: '#/components/schemas/MLText'
