package com.platformcommons.platform.service.search.application.utility;

import java.util.*;
import java.util.stream.Collectors;

public final class SkillMapper {


    private static final Map<String, String> skillMapping;

    static {
        Map<String, String> map = new HashMap<>();
        map.put("SKILL_CODE.PHOTOGRAPHY", "OPPORTUNITY_SKILLS.PHOTOGRAPHY_&_VIDEO");
        map.put("SKILL_CODE.PUBLIC_SPEAKING", "OPPORTUNITY_SKILLS.COMMUNICATIONS");
        map.put("SKILL_CODE.MARKETING", "OPPORTUNITY_SKILLS.MARKETING");
        map.put("SKILL_CODE.SOCIAL_MEDIA", "OPPORTUNITY_SKILLS.SOCIAL_MEDIA");
        map.put("SKILL_CODE.RESEARCH_DEVELOPMENT", "OPPORTUNITY_SKILLS.RESEARCH");
        map.put("SKILL_CODE.ACCOUNTING_FINANCE", "OPPORTUNITY_SKILLS.ACCOUNTING");
        map.put("SKILL_CODE.LAW", "OPPORTUNITY_SKILLS.CORPORATE_LAW");
        map.put("SKILL_CODE.APP_WEB_DEVELOPMENT", "OPPORTUNITY_SKILLS.WEB_DEVELOPMENT");
        map.put("SKILL_CODE.SOFTWARE_DEVELOPMENT", "OPPORTUNITY_SKILLS.INFORMATION_TECHNOLOGY");
        map.put("SKILL_CODE.CINEMATOGRAPHY", "OPPORTUNITY_SKILLS.PHOTOGRAPHY_&_VIDEO");
        map.put("SKILL_CODE.SALES", "OPPORTUNITY_SKILLS.SALES");
        map.put("SKILL_CODE.CONTENT_WRITING", "OPPORTUNITY_SKILLS.WRITING");
        map.put("SKILL_CODE.TEACHING_FACILITATION", "OPPORTUNITY_SKILLS.TEACHING_&_TRAINING");
        map.put("SKILL_CODE.FUNDRAISING", "OPPORTUNITY_SKILLS.FUNDRAISING");
        map.put("SKILL_CODE.RESEARCH", "OPPORTUNITY_SKILLS.RESEARCH");
        map.put("SKILL_CODE.MONITORING_EVALUATION", "OPPORTUNITY_SKILLS.MONITORING&_EVALUATION");
        map.put("SKILL_CODE.CONTEXT_OF_EDUCATION_SYSTEM", "OPPORTUNITY_SKILLS.CONTEXT_OF_EDUCATION_SYSTEM");
        map.put("SKILL_CODE.PROGRAM_IMPLEMENTATION", "OPPORTUNITY_SKILLS.PROGRAM_IMPLEMENTATION");
        map.put("SKILL_CODE.COMMUNITY_ENGAGEMENT", "OPPORTUNITY_SKILLS.COMMUNITY_ENGAGEMENT");
        map.put("SKILL_CODE.TEAM_MANAGEMENT", "OPPORTUNITY_SKILLS.TEAM_MANAGEMENT");
        map.put("SKILL_CODE.PROJECT_MANAGEMENT", "OPPORTUNITY_SKILLS.PROJECT_MANAGEMENT");
        map.put("SKILL_CODE.DATA_DRIVEN_DECISION_MAKING", "OPPORTUNITY_SKILLS.DATA_DRIVEN_DECISION_MAKING");
        map.put("SKILL_CODE.LOGICAL_REASONING", "OPPORTUNITY_SKILLS.LOGICAL_REASONING");
        map.put("SKILL_CODE.PROGRAM_MANAGEMENT", "OPPORTUNITY_SKILLS.PROGRAM_MANAGEMENT");
        map.put("SKILL_CODE.STRATEGIC_THINKING", "OPPORTUNITY_SKILLS.STRATEGIC_THINKING");
        map.put("SKILL_CODE.CONFLICT_RESOLUTION", "OPPORTUNITY_SKILLS.CONFLICT_RESOLUTION");
        map.put("SKILL_CODE.CLASSROOM_MANAGEMENT", "OPPORTUNITY_SKILLS.CLASSROOM_MANAGEMENT");
        map.put("SKILL_CODE.UNIT_PLANNING", "OPPORTUNITY_SKILLS.UNIT_PLANNING");
        map.put("SKILL_CODE.STAKEHOLDER_MANAGEMENT", "OPPORTUNITY_SKILLS.STAKEHOLDER_MANAGEMENT");
        map.put("SKILL_CODE.ASSESSMENT_CREATION", "OPPORTUNITY_SKILLS.ASSESSMENT_CREATION");
        map.put("SKILL_CODE.CARE_NURTURING", "OPPORTUNITY_SKILLS.CARE_AND_NURTURING");
        map.put("SKILL_CODE.ACTIVE_LISTENING", "OPPORTUNITY_SKILLS.ACTIVE_LISTENING");
        map.put("SKILL_CODE.COMMUNICATION", "OPPORTUNITY_SKILLS.COMMUNICATIONS");
        map.put("SKILL_CODE.DATA_ANALYSIS", "OPPORTUNITY_SKILLS.DATA_ANALYSIS");
        map.put("SKILL_CODE.PROBLEM_SOLVING", "OPPORTUNITY_SKILLS.PROBLEM_SOLVING");
        map.put("SKILL_CODE.GROWTH_MINDSET", "OPPORTUNITY_SKILLS.GROWTH_MINDSET");
        map.put("SKILL_CODE.CRITICAL_THINKING", "OPPORTUNITY_SKILLS.CRITICAL_THINKING");
        map.put("SKILL_CODE.LEADERSHIP", "OPPORTUNITY_SKILLS.LEADERSHIP_DEVELOPMENT");
        map.put("SKILL_CODE.COLLABORATION", "OPPORTUNITY_SKILLS.TEAM_MANAGEMENT");

        skillMapping = Collections.unmodifiableMap(map);
    }

    public static Set<String> mapUserSkillsToOpportunitySkills(Set<String> userSkills) {
        return userSkills.stream()
                .filter(skillMapping::containsKey)
                .map(skillMapping::get)
                .collect(Collectors.toSet());
    }
}
