openapi: 3.0.0
info:
  title: test
  version: '1.0'
tags:
 - name: DataSource
 - name: Dataset
 - name: DatasetTenant
 - name: DatasetGroup

paths:
  /api/v1/datasource/page:
    get:
      summary: Get By Page
      tags:
        - DataSource
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DataSource'
      operationId: get-data-source-page
      parameters:
        - schema:
            type: integer
            format: int32
          in: query
          name: page
          required: true
        - schema:
            type: integer
            format: int32
          in: query
          name: size
          required: true
        - schema:
            type: string
          in: query
          name: sortBy
          required: false
        - schema:
            type: string
          in: query
          name: direction
          required: false
  /api/v1/datasource:
    get:
      summary: Get By Id
      tags:
        - DataSource
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataSource'
      operationId: get-data-source-by-id
      parameters:
        - schema:
            type: integer
            format: int64
          in: query
          name: id
          required: true
    post:
      summary: ''
      operationId: add-data-source
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: integer
                format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataSource'
      tags:
        - DataSource
    put:
      summary: ''
      operationId: update-data-source
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataSource'
      tags:
        - DataSource
      description: ''
    delete:
      summary: ''
      operationId: delete-data-source
      responses:
        '204':
          description: No Content
      parameters:
        - schema:
            type: integer
            format: int64
          in: query
          name: id
          required: true
        - schema:
            type: string
          in: query
          name: reason
          required: true
      tags:
        - DataSource
  /api/v1/datasets/page:
    get:
      summary: Get By Page
      tags:
        - Dataset
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dataset'
      operationId: get-dataset-page
      parameters:
        - schema:
            type: integer
            format: int32
          in: query
          name: page
          required: true
        - schema:
            type: integer
            format: int32
          in: query
          name: size
          required: true
        - schema:
            type: string
          in: query
          name: sortBy
          required: false
        - schema:
            type: string
          in: query
          name: direction
          required: false


  /api/v1/dataset-groups:
    get:
      summary: Get By Id
      tags:
        - DatasetGroup
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatasetGroup'
      operationId: get-dataset-group
      parameters:
        - schema:
            type: integer
            format: int64
          in: query
          name: id
          required: true
      description: This API returns DatasetGroup
    post:
      summary: ''
      operationId: add-dataset-group
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: integer
                format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DatasetGroup'
      tags:
        - DatasetGroup
      description: This API add new DatasetGroup
  /api/v1/dataset-groups/{datasetGroupId}/datasets:
    post:
      summary: ''
      operationId: add-dataset-to-dataset-group
      parameters:
        - schema:
            type: integer
            format: int64
          in: path
          name: datasetGroupId
          required: true
        - schema:
            type: integer
            format: int64
          in: query
          name: datasetId
          required: true
      responses:
        '200':
          description: OK
      tags:
        - DatasetGroup
      description: This API adds existing Dataset to an existing DatasetGroup
  /api/v1/dataset-groups/{datasetGroupId}/tenant-info:
    post:
      summary: ''
      operationId: add-tenant-info-to-dataset-group
      parameters:
        - schema:
            type: integer
            format: int64
          in: path
          name: datasetGroupId
          required: true
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TenantInfo'
      tags:
        - DatasetGroup
      description: This API adds TenantInfo to DatasetGroup

  /api/v1/dataset-groups/tenant-info/{datasetGroupCode}:
    post:
      summary: ''
      operationId: add-tenant-info-to-dataset-group-code
      parameters:
        - schema:
            type: string
          in: path
          name: datasetGroupCode
          required: true
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TenantInfo'
      tags:
        - DatasetGroup
      description: This API adds TenantInfo to DatasetGroup


components:
  schemas:
    DataSource:
      title: DataSource
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        url:
          type: string
        user:
          type: string
        password:
          type: string
        dataSourceDriver:
          type: string
        isDefaultDataSource:
          type: boolean
    Dataset:
      title: Dataset
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        queryText:
          type: string
        defaultParamMap:
          type: string
        datasetType:
          type: string
        isCronEnabled:
          type: boolean
        isRawInputUpload:
          type: integer
          format: int64
        isExposed:
          type: boolean
#        dataSetParams:
#          type: array
#          items:
#            $ref: '#/components/schemas/DatasetParam'

    DatasetParam:
      title: DatasetParam
      type: object
      properties:
        id:
          type: integer
          format: int64
        paramName:
          type: string
        dataType:
          type: string
        position:
          type: integer
          format: int32
    DatasetGroup:
      title: DatasetGroup
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        code:
          type: string
        datasets:
          type: array
          items:
            $ref: '#/components/schemas/Dataset'
        allowedTenants:
          type: array
          items:
            $ref: '#/components/schemas/TenantInfo'
    TenantInfo:
      title: TenantInfo
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tenantId:
          type: integer
          format: int64