openapi: 3.0.0
info:
  title: test
  version: '1.0'
tags:
 - name: ReportFlag

paths:
  /api/v1/report-flag/page:
    get:
      summary: Get By Page
      tags:
        - ReportFlag
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReportFlag'
      operationId: get-report-flag-page
      parameters:
        - schema:
            type: integer
            format: int32
          in: query
          name: page
          required: true
        - schema:
            type: integer
            format: int32
          in: query
          name: size
          required: true
  /api/v1/report-flag:
    get:
      summary: Get By Id
      tags:
        - ReportFlag
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReportFlag'
      operationId: get-report-flag
      parameters:
        - schema:
            type: integer
            format: int64
          in: query
          name: id
          required: true
    post:
      summary: ''
      operationId: post-report-flag
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: integer
                format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReportFlag'
      tags:
        - ReportFlag
    put:
      summary: ''
      operationId: put-report-flag
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReportFlag'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReportFlag'
      tags:
        - ReportFlag
      description: ''
    delete:
      summary: ''
      operationId: delete-report-flag
      responses:
        '204':
          description: No Content
      parameters:
        - schema:
            type: integer
            format: int64
          in: query
          name: id
          required: true
        - schema:
            type: string
          in: query
          name: reason
          required: true
      tags:
        - ReportFlag

components:
  schemas:
    ReportFlag:
      title: ReportFlag
      type: object
      properties:
        id:
          type: integer
          format: int64
        reportType:
          type: string
        reportStatus:
          type: string
        reportedOnEntityId:
          type: integer
          format: int64
        reportedOnEntityType:
          type: string
        reporteeRemarks:
          type: string
        reportedOnDateTime:
          type: string
          format: date-time
        reviewedByActorId:
          type: integer
          format: int64
        reviewedByActorType:
          type: string
        reviewerRemarks:
          type: string
        reportText:
          type: string
        reportedByActorId:
          type: integer
          format: int64
        reportedByActorType:
          type: string
