package com.platformcommons.platform.service.domain.messaging.constants;

public class EventConstants {

    public static  final String APP_CREATED="COMMONS_DOMAIN_SERVICE.APP_CREATED";  // EventDTO<AppEventDTO>
    public static  final String APP_UPDATED="COMMONS_DOMAIN_SERVICE.APP_UPDATED";
    public static  final String DOMAIN_CREATED="COMMONS_DOMAIN_SERVICE.DOMAIN_CREATED"; // EventDTO<DomainEventDTO>
    public static  final String DOMAIN_UPDATED="COMMONS_DOMAIN_SERVICE.DOMAIN_UPDATED";
    public static  final String DOMAIN_HIERARCHY_CREATED="COMMONS_DOMAIN_SERVICE.DOMAIN_HIERARCHY_CREATED"; // EventDTO<DomainHIERARCHYEventDTO>
    public static  final String DOMAIN_HIERARCHY_UPDATED="COMMONS_DOMAIN_SERVICE.DOMAIN_HIERARCHY_UPDATED";
    public static  final String USE_CASE_CREATED="COMMONS_DOMAIN_SERVICE.USE_CASE_CREATED"; // EventDTO<UseCaseEventDTO>
    public static  final String USE_CASE_UPDATED="COMMONS_DOMAIN_SERVICE.USE_CASE_UPDATED";
    public static final String SKILL_CREATED = "COMMONS_DOMAIN_SERVICE.SKILL_CREATED"; // EventDTO<SkillEventDTO>
    public static final String SKILL_UPDATED = "COMMONS_DOMAIN_SERVICE.SKILL_UPDATED";
    public static final String SKILL_HIERARCHY_CREATED = "COMMONS_DOMAIN_SERVICE.SKILL_HIERARCHY_CREATED"; // EventDTO<SkillHierarchyEventDTO>
    public static final String SKILL_HIERARCHY_UPDATED = "COMMONS_DOMAIN_SERVICE.SKILL_HIERARCHY_UPDATED";

    public static  final String TAG_CREATED="COMMONS_DOMAIN_SERVICE.TAG_CREATED";  // EventDTO<TagDTO>
    public static  final String TAG_UPDATED="COMMONS_DOMAIN_SERVICE.TAG_UPDATED";

    public static final String GENERIC_PRODUCT_TAG_CREATED_OR_UPDATED = "COMMONS_PRODUCT_SERVICE.GENERIC_PRODUCT_TAG_CREATED_OR_UPDATED";;
    public static final String GENERIC_PRODUCT_TAG_DELETED = "COMMONS_PRODUCT_SERVICE.GENERIC_PRODUCT_TAG_DELETED";
    public static final String GENERIC_PRODUCT_TAG_SYNCED = "COMMONS_PRODUCT_SERVICE.GENERIC_PRODUCT_TAG_SYNCED";
    public static final String GENERIC_PRODUCT_VARIETY_TAG_CREATED_OR_UPDATED = "COMMONS_PRODUCT_SERVICE.GENERIC_PRODUCT_VARIETY_TAG_CREATED_OR_UPDATED";
    public static final String GENERIC_PRODUCT_VARIETY_TAG_SYNCED = "COMMONS_PRODUCT_SERVICE.GENERIC_PRODUCT_VARIETY_TAG_SYNCED";
    public static final String GENERIC_PRODUCT_VARIETY_TAG_DELETED = "COMMONS_PRODUCT_SERVICE.GENERIC_PRODUCT_VARIETY_TAG_DELETED";

    public static final String GENERIC_PRODUCT_VARIETY_RETAGGED_FOR_DOMAIN_SERVICE = "COMMONS_PRODUCT_SERVICE.GENERIC_PRODUCT_VARIETY_RETAGGED_FOR_DOMAIN_SERVICE";

    public static final String GROUP_ID="COMMONS-DOMAIN-SERVICE";
}
